// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store/update.proto

package store // import "github.com/socketfunc/proto/store"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Update_Op int32

const (
	Update_INC   Update_Op = 0
	Update_SET   Update_Op = 1
	Update_UNSET Update_Op = 2
)

var Update_Op_name = map[int32]string{
	0: "INC",
	1: "SET",
	2: "UNSET",
}
var Update_Op_value = map[string]int32{
	"INC":   0,
	"SET":   1,
	"UNSET": 2,
}

func (x Update_Op) String() string {
	return proto.EnumName(Update_Op_name, int32(x))
}
func (Update_Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_update_f611a28d2af2427f, []int{0, 0}
}

type Update struct {
	Op                   Update_Op `protobuf:"varint,1,opt,name=op,proto3,enum=store.Update_Op" json:"op,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                *Value    `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_update_f611a28d2af2427f, []int{0}
}
func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (dst *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(dst, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetOp() Update_Op {
	if m != nil {
		return m.Op
	}
	return Update_INC
}

func (m *Update) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Update) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Update)(nil), "store.Update")
	proto.RegisterEnum("store.Update_Op", Update_Op_name, Update_Op_value)
}

func init() { proto.RegisterFile("store/update.proto", fileDescriptor_update_f611a28d2af2427f) }

var fileDescriptor_update_f611a28d2af2427f = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2e, 0xc9, 0x2f,
	0x4a, 0xd5, 0x2f, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x05, 0x8b, 0x49, 0x09, 0x42, 0xa4, 0xca, 0x12, 0x73, 0x4a, 0xa1, 0x32, 0x4a, 0xad, 0x8c, 0x5c,
	0x6c, 0xa1, 0x60, 0xa5, 0x42, 0x0a, 0x5c, 0x4c, 0xf9, 0x05, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c,
	0x46, 0x02, 0x7a, 0x60, 0xa5, 0x7a, 0x10, 0x29, 0x3d, 0xff, 0x82, 0x20, 0xa6, 0xfc, 0x02, 0x21,
	0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b,
	0x48, 0x89, 0x8b, 0x15, 0x6c, 0x9e, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0xb7, 0x11, 0x0f, 0x54, 0x63,
	0x18, 0x48, 0x2c, 0x08, 0x22, 0xa5, 0xa4, 0xc8, 0xc5, 0xe4, 0x5f, 0x20, 0xc4, 0xce, 0xc5, 0xec,
	0xe9, 0xe7, 0x2c, 0xc0, 0x00, 0x62, 0x04, 0xbb, 0x86, 0x08, 0x30, 0x0a, 0x71, 0x72, 0xb1, 0x86,
	0xfa, 0x81, 0x98, 0x4c, 0x4e, 0xca, 0x51, 0x8a, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9,
	0xf9, 0xb9, 0xfa, 0xc5, 0xf9, 0xc9, 0xd9, 0xa9, 0x25, 0x69, 0xa5, 0x79, 0xc9, 0xfa, 0x60, 0x67,
	0xea, 0x83, 0x0d, 0x4d, 0x62, 0x03, 0x73, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xe6,
	0x84, 0xf2, 0xe3, 0x00, 0x00, 0x00,
}
