// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store/value.proto

package store // import "github.com/socketfunc/proto/store"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Value_Type int32

const (
	Value_INT    Value_Type = 0
	Value_UINT   Value_Type = 1
	Value_FLOAT  Value_Type = 2
	Value_String Value_Type = 3
	Value_BOOL   Value_Type = 4
)

var Value_Type_name = map[int32]string{
	0: "INT",
	1: "UINT",
	2: "FLOAT",
	3: "String",
	4: "BOOL",
}
var Value_Type_value = map[string]int32{
	"INT":    0,
	"UINT":   1,
	"FLOAT":  2,
	"String": 3,
	"BOOL":   4,
}

func (x Value_Type) String() string {
	return proto.EnumName(Value_Type_name, int32(x))
}
func (Value_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_value_154fd0aeed9c2416, []int{0, 0}
}

type Value struct {
	Type                 Value_Type `protobuf:"varint,1,opt,name=type,proto3,enum=store.Value_Type" json:"type,omitempty"`
	Data                 []byte     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_value_154fd0aeed9c2416, []int{0}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetType() Value_Type {
	if m != nil {
		return m.Type
	}
	return Value_INT
}

func (m *Value) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Entity struct {
	Data                 map[string]*Value `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_value_154fd0aeed9c2416, []int{1}
}
func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (dst *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(dst, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetData() map[string]*Value {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "store.Value")
	proto.RegisterType((*Entity)(nil), "store.Entity")
	proto.RegisterMapType((map[string]*Value)(nil), "store.Entity.DataEntry")
	proto.RegisterEnum("store.Value_Type", Value_Type_name, Value_Type_value)
}

func init() { proto.RegisterFile("store/value.proto", fileDescriptor_value_154fd0aeed9c2416) }

var fileDescriptor_value_154fd0aeed9c2416 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdd, 0xfc, 0xd3, 0x4c, 0x8b, 0xa4, 0x73, 0xb1, 0x78, 0x8a, 0x11, 0x21, 0x20, 0x6c,
	0x20, 0x5e, 0xa4, 0x37, 0x8b, 0x11, 0x84, 0x62, 0x20, 0x46, 0x0f, 0xde, 0xd2, 0xb8, 0xd6, 0x50,
	0x4d, 0x42, 0x3a, 0x11, 0x02, 0xe2, 0x67, 0x97, 0x9d, 0x14, 0xf1, 0xf6, 0xf6, 0xfd, 0x66, 0x77,
	0xdf, 0x1b, 0x98, 0xed, 0xa8, 0xe9, 0x54, 0xf4, 0x55, 0x7c, 0xf4, 0x4a, 0xb6, 0x5d, 0x43, 0x0d,
	0xda, 0x6c, 0x05, 0x3f, 0x60, 0x3f, 0x6b, 0x17, 0x2f, 0xc0, 0xa2, 0xa1, 0x55, 0x73, 0xe1, 0x8b,
	0xf0, 0x38, 0x9e, 0x49, 0xc6, 0x92, 0x99, 0xcc, 0x87, 0x56, 0x65, 0x8c, 0x11, 0xc1, 0x7a, 0x2d,
	0xa8, 0x98, 0x1b, 0xbe, 0x08, 0xa7, 0x19, 0xeb, 0x60, 0x01, 0x96, 0x9e, 0xc0, 0x43, 0x30, 0xef,
	0x1f, 0x72, 0xef, 0x00, 0x8f, 0xc0, 0x7a, 0xd2, 0x4a, 0xa0, 0x0b, 0xf6, 0xdd, 0x2a, 0xbd, 0xc9,
	0x3d, 0x03, 0x01, 0x9c, 0x47, 0xea, 0xaa, 0x7a, 0xe3, 0x99, 0x7a, 0x60, 0x99, 0xa6, 0x2b, 0xcf,
	0x0a, 0xbe, 0xc1, 0x49, 0x6a, 0xaa, 0x68, 0xc0, 0xcb, 0xfd, 0xcb, 0xc2, 0x37, 0xc3, 0x49, 0x7c,
	0xb2, 0x0f, 0x30, 0x42, 0x79, 0x5b, 0x50, 0x91, 0xd4, 0xd4, 0x0d, 0xe3, 0x97, 0xa7, 0x09, 0xb8,
	0x7f, 0x16, 0x7a, 0x60, 0x6e, 0xd5, 0xc0, 0xc9, 0xdd, 0x4c, 0x4b, 0x0c, 0xc0, 0xe6, 0xae, 0x1c,
	0x73, 0x12, 0x4f, 0xff, 0xb7, 0xc9, 0x46, 0xb4, 0x30, 0xae, 0xc5, 0xf2, 0xfc, 0xe5, 0x6c, 0x53,
	0xd1, 0x7b, 0xbf, 0x96, 0x65, 0xf3, 0x19, 0xed, 0x9a, 0x72, 0xab, 0xe8, 0xad, 0xaf, 0xcb, 0x88,
	0x77, 0x14, 0xf1, 0xad, 0xb5, 0xc3, 0x87, 0xab, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x28,
	0x49, 0x08, 0x45, 0x01, 0x00, 0x00,
}
